#!/bin/bash
#
# StorjMailAlert - Common Functions Library
# This file contains shared functions used by all check scripts
#

set -euo pipefail

# Determine script directory (works even when sourced)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/config.env"
NODES_FILE="${SCRIPT_DIR}/nodes.json"
LOG_DIR="${SCRIPT_DIR}/logs"
TMP_DIR="${SCRIPT_DIR}/tmp"

# Global arrays for collecting alerts
declare -a ALERT_MESSAGES=()
declare -a ALERT_DETAILS=()

# ------------------------------------------------------------------------------
# Configuration Loading
# ------------------------------------------------------------------------------

load_config() {
    # Throw error if config file is missing
    if [[ ! -f "$CONFIG_FILE" ]]; then
        echo "ERROR: Configuration file not found: $CONFIG_FILE" >&2
        echo "Run ./setup.sh to create one or copy from config/config.env.example" >&2
        exit 1
    fi

    # shellcheck source=/dev/null
    source "$CONFIG_FILE"

    # Set defaults for optional values
    ALERT_EMAIL="${ALERT_EMAIL:-}"
    CHECK_INTERVAL="${CHECK_INTERVAL:-15}"
    ERROR_PERCENT_THRESHOLD="${ERROR_PERCENT_THRESHOLD:-5}"
    IS_NODE_OPERATOR="${IS_NODE_OPERATOR:-true}"
    ENABLE_LOG_CHECK="${ENABLE_LOG_CHECK:-true}"
    ENABLE_NODE_CHECK="${ENABLE_NODE_CHECK:-true}"
    ENABLE_DISK_CHECK="${ENABLE_DISK_CHECK:-true}"
    ENABLE_NOIP_CHECK="${ENABLE_NOIP_CHECK:-false}"
    CONTAINER_PREFIX="${CONTAINER_PREFIX:-storagenode}"

    # Override paths if not set in config
    LOG_DIR="${LOG_DIR:-${SCRIPT_DIR}/logs}"
    TMP_DIR="${TMP_DIR:-${SCRIPT_DIR}/tmp}"

    # Ensure directories exist
    mkdir -p "$LOG_DIR" "$TMP_DIR"

    # Validate required settings
    if [[ -z "$ALERT_EMAIL" ]]; then
        log_error "ALERT_EMAIL is not set in config.env"
        exit 1
    fi
}

# ------------------------------------------------------------------------------
# Logging Functions
# ------------------------------------------------------------------------------

# Main logging function
# _log <level> <message>
# Levels: INFO, ERROR, WARN, DEBUG
_log() {
    local level="$1"
    local message="$2"
    local timestamp
    timestamp="$(date '+%Y-%m-%d %H:%M:%S')"
    echo "[$timestamp] [$level] $message"
}

log_info() {
    _log "INFO" "$1"
}

log_error() {
    _log "ERROR" "$1" >&2
}

log_warn() {
    _log "WARN" "$1"
}

log_debug() {
    if [[ "${DEBUG:-false}" == "true" ]]; then
        _log "DEBUG" "$1"
    fi
}

# Main events logged to file
log_to_file() {
    local log_file="${LOG_DIR}/storjMailAlert.log"
    local message="$1"
    local timestamp
    timestamp="$(date '+%Y-%m-%d %H:%M:%S')"
    echo "[$timestamp] $message" >> "$log_file"
}

# ------------------------------------------------------------------------------
# Email Functions
# ------------------------------------------------------------------------------

send_email() {
    local subject="$1"
    local body="$2"

    if ! command -v ssmtp &> /dev/null; then
        log_error "ssmtp is not installed. Cannot send email."
        return 1
    fi

    echo -e "Subject: $subject\n\n$body" | /usr/sbin/ssmtp -F "$(get_hostname)" "$ALERT_EMAIL"
    log_info "Email sent to $ALERT_EMAIL: $subject"
}

# Add message to alert queue (for aggregated alerts)
add_alert() {
    local category="$1"
    local message="$2"
    ALERT_MESSAGES+=("[$category] $message")
}

add_alert_detail() {
    local detail="$1"
    ALERT_DETAILS+=("$detail")
}

# Send all queued alerts in a single email
send_aggregated_alerts() {
    if [[ ${#ALERT_MESSAGES[@]} -eq 0 ]]; then
        log_info "No alerts to send"
        return 0
    fi

    local subject
    subject="Storj Alert from $(get_hostname): ${#ALERT_MESSAGES[@]} issue(s) detected"
    local body="The following issues were detected:\n\n"

    for msg in "${ALERT_MESSAGES[@]}"; do
        body+="- $msg\n"
    done

    if [[ ${#ALERT_DETAILS[@]} -gt 0 ]]; then
        body+="\n\n===== DETAILS =====\n\n"
        for detail in "${ALERT_DETAILS[@]}"; do
            body+="$detail\n"
        done
    fi

    body+="\n\n---\nGenerated by StorjMailAlert at $(date)"

    send_email "$subject" "$body"
}

# ------------------------------------------------------------------------------
# Temp File Management
# ------------------------------------------------------------------------------

declare -a TEMP_FILES=()

create_temp_file() {
    local prefix="${1:-storj}"
    local tmp_file
    tmp_file="$(mktemp "${TMP_DIR}/${prefix}.XXXXXX")"
    TEMP_FILES+=("$tmp_file")
    echo "$tmp_file"
}

cleanup_temp_files() {
    for f in "${TEMP_FILES[@]:-}"; do
        if [[ -f "$f" ]]; then
            rm -f "$f"
        fi
    done
    TEMP_FILES=()
}

# Set trap for cleanup on exit
trap cleanup_temp_files EXIT

# ------------------------------------------------------------------------------
# Dependency Checking
# ------------------------------------------------------------------------------

require_command() {
    local cmd="$1"
    local package="${2:-$1}"

    if ! command -v "$cmd" &> /dev/null; then
        log_error "Required command '$cmd' not found. Install with: apt install $package"
        return 1
    fi
    return 0
}

check_dependencies() {
    local missing=0

    require_command "ssmtp" "ssmtp" || ((missing++))
    require_command "jq" "jq" || ((missing++))
    require_command "bc" "bc" || ((missing++))
    require_command "curl" "curl" || ((missing++))

    if [[ "$IS_NODE_OPERATOR" == "true" ]]; then
        require_command "docker" "docker.io" || ((missing++))
    fi

    return $missing
}

# ------------------------------------------------------------------------------
# Helper Functions
# ------------------------------------------------------------------------------

# Get current hostname
get_hostname() {
    hostname || xargs < /etc/hostname 2>/dev/null || echo 'unknown'
}

# Check if current machine matches a given name
is_local_machine() {
    local name="$1"
    local current_host
    current_host="$(get_hostname)"
    [[ "$name" == "$current_host" ]]
}

# Get container name for a given node index.
# Uses the default convention: storagenode, storagenode2, storagenode3, ...
get_container_name() {
    local index="$1"
    if [[ "$index" -eq 1 ]]; then
        echo "${CONTAINER_PREFIX}"
    else
        echo "${CONTAINER_PREFIX}${index}"
    fi
}

# Get mount point for a given node index.
# Uses the default convention: /mnt/storj, /mnt/storj2, /mnt/storj3, ...
get_mount_point() {
    local index="$1"
    if [[ "$index" -eq 1 ]]; then
        echo "/mnt/storj"
    else
        echo "/mnt/storj${index}"
    fi
}

# ------------------------------------------------------------------------------
# Node Resolution (nodes.json aware)
# ------------------------------------------------------------------------------

# Resolve the container name for a node entry from nodes.json.
# Uses the custom "containerName" field if present, otherwise falls back to convention.
# Args: $1 = node JSON object, $2 = node index (1-based) within the server
resolve_container_name() {
    local node_json="$1"
    local index="$2"
    local custom
    custom="$(echo "$node_json" | jq -r '.containerName // empty')"

    if [[ -n "$custom" ]]; then
        echo "$custom"
    else
        get_container_name "$index"
    fi
}

# Resolve the mount point for a node entry from nodes.json.
# Uses the custom "mountPoint" field if present, otherwise falls back to convention.
# Args: $1 = node JSON object, $2 = node index (1-based) within the server
resolve_mount_point() {
    local node_json="$1"
    local index="$2"
    local custom
    custom="$(echo "$node_json" | jq -r '.mountPoint // empty')"

    if [[ -n "$custom" ]]; then
        echo "$custom"
    else
        get_mount_point "$index"
    fi
}

# Get all local node entries from nodes.json for the current machine.
# Outputs one JSON object per line: { port, containerName, mountPoint }
# with convention-based defaults filled in for missing fields.
# Returns 1 if no local nodes found or nodes.json doesn't exist.
get_local_nodes() {
    if [[ ! -f "$NODES_FILE" ]]; then
        return 1
    fi

    # Find the server entry matching this hostname
    local server
    server="$(jq -c --arg name "$(get_hostname)" '.servers[] | select(.name == $name)' "$NODES_FILE" 2>/dev/null)"

    if [[ -z "$server" ]]; then
        return 1
    fi

    # Iterate over nodes and fill in defaults
    local index=1
    while IFS= read -r node; do
        local port container_name mount_point
        port="$(echo "$node" | jq -r '.port')"
        container_name="$(resolve_container_name "$node" "$index")"
        mount_point="$(resolve_mount_point "$node" "$index")"

        echo "{\"port\":${port},\"containerName\":\"${container_name}\",\"mountPoint\":\"${mount_point}\",\"index\":${index}}"
        ((index++))
    done < <(echo "$server" | jq -c '.nodes[]')
}

# Validate email format (basic check)
validate_email() {
    local email="$1"
    if [[ "$email" =~ ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$ ]]; then
        return 0
    fi
    return 1
}

# Validate positive integer
validate_positive_int() {
    local value="$1"
    if [[ "$value" =~ ^[0-9]+$ ]] && [[ "$value" -gt 0 ]]; then
        return 0
    fi
    return 1
}
